version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: php_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - appnet

  webserver:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.env.testing:/var/www/html/.env
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - appnet

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "65535:65535"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
  
